app:
  root-redirect: http://localhost:8059/
  storage: storage/
  hash-types: [SHA256, SHA1, MD5]
  api-base-url: http://localhost:8059/
  api-title: "JavaDucks API"
  api-version: "v1"
  maven:
    repositories:
      groups:
        maven-public:
          members:
            - maven-central
            - sonatype-snapshots
            - sonatype-snapshots-s01
            - papermc-public
      proxied:
        maven-central:
          url: https://repo1.maven.org/maven2/
          cache: ./storage/cache/maven-central/
        sonatype-snapshots:
          url: https://oss.sonatype.org/content/repositories/snapshots/
          cache: ./storage/cache/sonatype-snapshots/
        sonatype-snapshots-s01:
          url: https://s01.oss.sonatype.org/content/repositories/snapshots/
          cache: ./storage/cache/sonatype-snapshots-s01/
        papermc-public:
          url: https://repo.papermc.io/repository/maven-public/
          cache: ./storage/cache/papermc-public/

  endpoints:
    - name: 'folia'
      versions:
        - name: '1.19'
          path: 'dev.folia:folia-api:1.19.4-R0.1-SNAPSHOT'
          type: 'SNAPSHOT'
        - name: '1.20'
          path: 'dev.folia:folia-api:1.20.4-R0.1-SNAPSHOT'
          type: 'SNAPSHOT'
    - name: 'paper'
      versions:
        - name: '1.20'
          path: 'io.papermc.paper:paper-api:1.20.4-R0.1-SNAPSHOT'
          type: 'SNAPSHOT'
        - name: '1.20.6'
          path: 'io.papermc.paper:paper-api:1.20.6-R0.1-SNAPSHOT'
          type: 'SNAPSHOT'

server:
  port : 8059
logging:
  level:
    root: INFO
    com.seiama.javaducks: DEBUG
    com.seiama.javaducks.*: DEBUG
